SP_ASPNET_1/Controllers/BlogPostController.cs
using SP_ASPNET_1.DbFiles.Operations;
using SP_ASPNET_1.Models;
using SP_ASPNET_1.ViewModels;
using System.Web.Mvc;
using System.Web.Routing;
using SP_ASPNET_1.BusinessLogic;
using System;
using Microsoft.AspNet.Identity;
using System.Net;
using System.Web;
using Microsoft.AspNet.Identity.Owin;
using Newtonsoft.Json;

namespace SP_ASPNET_1.Controllers
{
    [RoutePrefix("Blog")]
    public class BlogPostController : Controller
    {

        private readonly BlogPostOperations _blogPostOperations = new BlogPostOperations();

        [Route("")]
        [HttpGet]
        public ActionResult Index()
        {
            BlogIndexViewModel result = this._blogPostOperations.GetBlogIndexViewModel();
            ViewBag.Title = "Blog";
            return View(result);
        }


        [Route("Detail/{id:int?}")]
        [HttpGet]
        public ActionResult SinglePost(int? id)
        {
            ViewBag.Title = "single post";

            
            BlogSinglePostViewModel modelView;

            if (id == null)
            {
                modelView = this._blogPostOperations.GetLatestBlogPost();
            }
            else
            {
                modelView = this._blogPostOperations.GetBlogPostByIdFull(id.Value);
            }

            return View(modelView);
        }

        [Route("Detail/Random")]
        [HttpGet]
        public ActionResult RandomPost()
        {
            ViewBag.Title = "Random post";

            var viewModel = this._blogPostOperations.GetRandomBlogPost();

            return View("SinglePost", viewModel);
        }

        [Route("LatestPost")]
        [HttpGet]
        public ActionResult LatestPost()
        {
            var viewModel = this._blogPostOperations.GetLatestBlogPost();

            return this.PartialView("~/Views/BlogPost/_BlogPostRecentPartialView.cshtml", viewModel);
        }

        [Authorize(Roles = "Admin, Author, User")]
        [Route("LikePost/{id:int}")]
        [HttpPost]
        public ActionResult LikeBlogPost(int id)
        {
            BlogPost blogPost = this._blogPostOperations.GetBlogPostByIdD(id);
            if (blogPost == null)
            {
                return Json(new { PostLikes = -1, ResultState = "Fail", JsonRequestBehavior.AllowGet });
            }

            blogPost = this._blogPostOperations.LikeBlogPost(id, User.Identity.GetUserId());
            return Json(new { PostLikes = blogPost.Likes, ResultState = "Success", JsonRequestBehavior.AllowGet });
        }

        [Authorize(Roles = "Admin, Author")]
        [Route("Create")]
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin, Author")]
        [Route("Create")]
        [HttpPost]
        public ActionResult Create(BlogPost blogPost)
        {
            try
            {
                blogPost.DateTime = DateTime.Now;
                blogPost.AuthorID = User.Identity.GetUserId();

                if (ModelState.IsValid)
                {
                    this._blogPostOperations.Create(blogPost);

                    return RedirectToAction("SinglePost", blogPost.BlogPostID);
                }

                return View(blogPost);
            }
            catch
            {
                return View();
            }
        }

        [Authorize(Roles = "Admin, Author")]
        [Route("Edit/{id:int?}")]
        [HttpGet]
        public ActionResult EditBlogPost(int id)
        {
            BlogPost blogPost = this._blogPostOperations.GetBlogPostByIdD(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }

            var _userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            if (!_userManager.IsInRole(User.Identity.GetUserId(), "Admin") 
                && blogPost.AuthorID != User.Identity.GetUserId())
            {
                return Content(HttpStatusCode.Unauthorized.ToString(), "Unauthorized");
            }

            return View(blogPost);
        }

        [Authorize(Roles = "Admin, Author")]
        [Route("Edit/{id:int}")]
        [HttpPost]
        public ActionResult Edit(int id, BlogPost blogPost)
        {
            try
            {
                var postToEdit = this._blogPostOperations.GetBlogPostByIdD(id);
                var _userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();

                if (!_userManager.IsInRole(User.Identity.GetUserId(), "Admin")
                    && postToEdit.AuthorID != User.Identity.GetUserId())
                {
                    return Json(new { ResultState = "Unauthorized", JsonRequestBehavior.AllowGet });
                }

                postToEdit.Content = blogPost.Content;
                postToEdit.DateTime = blogPost.DateTime;
                postToEdit.Title = blogPost.Title;
                postToEdit.ImageUrl = blogPost.ImageUrl;
                postToEdit.BlogPostID = id;


                this._blogPostOperations.Update(postToEdit);

                return Json(new { ResultState = "Success", JsonRequestBehavior.AllowGet});
            }
            catch
            {
                return Json(new { ResultState = "Fail", JsonRequestBehavior.AllowGet });
            }
        }

        [Authorize(Roles = "Admin, Author")]
        [Route("Delete/{id:int}")]
        [HttpGet]
        public ActionResult Delete(int id)
        {
            try
            {
                var postToDelete = this._blogPostOperations.GetBlogPostByIdD(id);
                var _userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();

                if (!_userManager.IsInRole(User.Identity.GetUserId(), "Admin")
                    && postToDelete.AuthorID != User.Identity.GetUserId())
                {
                    return Content(HttpStatusCode.Unauthorized.ToString(), "Unauthorized");
                }

                this._blogPostOperations.Delete(id);

                return RedirectToAction("Index");
            }
            catch
            {
                return this.HttpNotFound();
            }
        }
    }
}

SP_ASPNET_1/Views/Shared/_Layout.cshtml
@using SP_ASPNET_1.BusinessLogic

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title @(ViewBag.Title != null ? "-" : "") .NET Developer Challenge</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <header class="header">
        <div class="header__navbar">
            <img #logo src="~/Content/images/logo.png" /> <span class="spacer"></span>
            <nav>
                <ul>
                    <li><a href="@Url.Action("Index", "Home")" class="@(@Html.IsActive("Home", "Index"))">HOME</a></li>
                    <li>
                        <a href="@Url.Action("About", "Home")" class="@(@Html.IsActive("Home", "About"))">ABOUT</a>
                        <ul>
                            <li><a href="@Url.Action("Product", "Home")" class="@(@Html.IsActive("Home", "Product"))">PRODUCT</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "BlogPost")" class="@(@Html.IsActive("BlogPost", "Index"))">BLOG</a>
                        <ul>
                            <li><a href="@Url.Action("RandomPost", "BlogPost")" class="@(@Html.IsActive("BlogPost", "RandomPost"))">RANDOM POST</a></li>
                        </ul>
                    </li>
                    <li><a href="@Url.Action("Contact", "Home")" class="@(@Html.IsActive("Home", "Contact"))">CONTACT</a></li>
                </ul>
                <ul class="navbar-nav mr-auto">
                    @Html.Partial("_LoginPartial")
                </ul>
            </nav>
        </div>
    </header>
    @RenderBody()
    <footer>
        <div>
            <div class="container">
                <div class="social">
                    <a href="#" class="facebook"></a>
                    <a href="#" class="googleplus"></a>
                    <a href="#" class="pinterest"></a> <a href="#" class="twitter"></a>
                </div>
                <p>© 2020 BBS</p>
            </div>
        </div>
    </footer>
    @RenderSection("scripts", required: false)
</body>
</html>